language: python
python:
- 2.6
- 2.7

install:
- pip install --use-mirrors \
    `python -c 'from setup import META; print " ".join(META["extras_require"]["testing"] + META["extras_require"]["build"] + META["install_requires"])'`
- pip install coveralls
- python setup.py develop

script:
- make remotes
- coverage run --source=tiddlywebplugins/bfw setup.py test
- coverage report -m

after_success: coveralls
